version: '3'
services:
  app:
    container_name: crud_api_app
    build: .
    command: go run main.go
    ports: 
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/crud_api
    depends_on:
      - db
       
  db:
    image: postgres
    container_name: crud_api_db
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=crud_api
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:


